//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTest
    {
        public int Id { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public System.DateTime SentDate { get; set; }
        public string Name { get; set; }
        public string ClaimsAdministrator { get; set; }
        public string Description { get; set; }
        public string Request { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Employer { get; set; }
    }
}
